services:
  discordbot:
    build:
      context: .
      dockerfile: discordbot/Dockerfile
      target: discordbot
    env_file: .env
    volumes:
      - ./database.sqlite:/app/database.sqlite

  telegrambot:
    build:
      context: .
      dockerfile: telegrambot/Dockerfile
      target: telegrambot
    env_file: .env
    volumes:
      - ./database.sqlite:/app/database.sqlite

  steam:
    build:
      context: .
      dockerfile: steam/Dockerfile
      target: steam
    env_file: .env
    volumes:
      - ./database.sqlite:/app/database.sqlite
